[book]
title = "The Osnomicon: x86 - 3rd Edition"
authors = ["Lock1"]
language = "id"
multilingual = false
src = "src"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/Lock1/IF2230-Sistem-Operasi-Book"
additional-css = ["src/css/helper.css"]

[output.html.playground]
editable = true
line-numbers = true

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = true
limit-results = 20